### ISSUE TITLE
Unknown error when using retryOnEmpty

### ISSUE THREAD

**Issue by catamounttechnology** [Leo4815162342/dukascopy-node#201]
```
const { getHistoricalRates } = require("dukascopy-node");

(async () => {
    const historicalRates = await getHistoricalRates({
        instrument: "eurusd",
        dates: {
            from: new Date("2017-10-06T00:00:00.000Z"),
            to: new Date("2017-10-07T00:00:00.000Z"),
        },
        timeframe: "tick",
        retryCount: 5,
        retryOnEmpty: true
    });

    console.log(historicalRates);
})();
```

>node s2.js
(node:105348) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\franco.tiveron\AppData\Roaming\npm\node_modules\dukascopy-node\dist\index.js:14524
          throw Error(errorMsg || "Unknown error");
                ^

Error: Unknown error
    at BufferFetcher.fetchBuffer (C:\Users\franco.tiveron\AppData\Roaming\npm\node_modules\dukascopy-node\dist\index.js:14524:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async C:\Users\franco.tiveron\AppData\Roaming\npm\node_modules\dukascopy-node\dist\index.js:14430:18
    at async Promise.all (index 1)
    at async BufferFetcher.fetch (C:\Users\franco.tiveron\AppData\Roaming\npm\node_modules\dukascopy-node\dist\index.js:14468:20)
    at async getHistoricalRates (C:\Users\franco.tiveron\AppData\Roaming\npm\node_modules\dukascopy-node\dist\index.js:15062:25)
    at async C:\Root\Work\FrancoTiveron\QuanTive\src\Services\Provider\QuanTive.Duka\s2.js:5:29

Node.js v22.11.0

**Comment by Leo4815162342** [comment]
thanks to PR from @VolatilCapital this should be fixed,
A new version with the fix has been released - [1.46.4](https://www.npmjs.com/package/dukascopy-node/v/1.46.4)
